# Generated by Django 3.2.1 on 2021-05-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20210507_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='staffregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='password',
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.myuser'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.myuser'),
        ),
    ]
