# Generated by Django 3.2.1 on 2021-05-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_stuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
